# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 811)
        MainWindow.setStyleSheet("background:white;\n"
"color:black;;")
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        self.styleSheet.setStyleSheet("#bgApp {\n"
"    backgroundr:white;\n"
"color:black;\n"
"border:1px solid gray;\n"
"}\n"
"\n"
"#contentTopBg{\n"
"background:white;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(16, 58, 89, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#rightButtons .QPushButton:hover { background-color: rgb(44, 49, 57); border-style: solid; border-radius: 4px; }\n"
"#rightButtons .QPushButton:pressed { background-color: rgb(23, 26, 30); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"border-radius:5px;\n"
"border:2px inset #333764;\n"
"background:#24284D;\n"
"border-bottom:2px inset black;\n"
"background-color:#24284D;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"border-radius:5px;\n"
"border:2px inset #333764;\n"
"background:#24284D;\n"
"border-bottom:2px inset black;\n"
"background-color:#24284D;\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {\n"
"color:white;\n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: rgb(33, 37, 43);\n"
"\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"color:white;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: transparent;;\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background:#28a6c8;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #EE8B7F;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background:#EE8B7F;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: #EE8B7F;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background:#EE8B7F;\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #EE8B7F;\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QGroupBox*/\n"
"QGroupBox  {\n"
"    border: 1px solid gray;\n"
"    border-color: #FF17365D;\n"
"    font-size: 16px;\n"
"    margin-top:40px;\n"
"font: 12pt \"Arial Rounded MT Bold\";\n"
"background:transparent;\n"
"}\n"
"\n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 5px 8000px 5px 8000px;\n"
"    background-color: #465083;\n"
"    color: rgb(255, 255, 255);\n"
"    margin-top:10px;\n"
"    font: 12pt \"Arial Rounded MT Bold\";\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QScrollArea*/\n"
"QScrollArea{\n"
"border:1px inset gray;\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton{\n"
"font: 10pt \"MS Shell Dlg 2\";}\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"\n"
"    background: 3px solid rgb(0, 170, 255);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QLabel */\n"
"QLabel{\n"
"color:white;\n"
"font: 11pt \"Arial Rounded MT Bold\";\n"
"background:transparent;\n"
"}\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(5, 5, 5, 5)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bgApp)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.contentTopBg = QtWidgets.QFrame(self.bgApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentTopBg.sizePolicy().hasHeightForWidth())
        self.contentTopBg.setSizePolicy(sizePolicy)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 0))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setStyleSheet("background:transparent;")
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_6.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.leftBox)
        self.label.setStyleSheet("color:black;\n"
"font: 12pt \"MS Sans Serif\";")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.titleRightInfo = QtWidgets.QFrame(self.leftBox)
        self.titleRightInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleRightInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.titleRightInfo)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(520, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setStyleSheet("background:transparent;")
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minimize-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(24, 24))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_5.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/restore-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon1)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(24, 24))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_5.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/close-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(24, 24))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_5.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons)
        self.verticalLayout_4.addWidget(self.contentTopBg)
        self.line = QtWidgets.QFrame(self.bgApp)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.frame_main = QtWidgets.QFrame(self.bgApp)
        self.frame_main.setStyleSheet("color:black;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_main)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_dnd = QtWidgets.QFrame(self.frame_3)
        self.frame_dnd.setStyleSheet("QFrame#frame_dnd{\n"
"border:3px dashed #7F7F7F;\n"
"border-radius:5px;\n"
"background:white;\n"
"}")
        self.frame_dnd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dnd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dnd.setObjectName("frame_dnd")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_dnd)
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.frame_dnd)
        self.label_5.setStyleSheet("color:#223568;font: 14pt \"Arial Rounded MT Bold\";\n"
"background:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.frame_11 = QtWidgets.QFrame(self.frame_dnd)
        self.frame_11.setStyleSheet("background:white;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(410, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.btn_upload = QtWidgets.QPushButton(self.frame_11)
        self.btn_upload.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_upload.setStyleSheet("background:transparent;border:none;")
        self.btn_upload.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/Upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_upload.setIcon(icon3)
        self.btn_upload.setIconSize(QtCore.QSize(128, 128))
        self.btn_upload.setObjectName("btn_upload")
        self.horizontalLayout_12.addWidget(self.btn_upload)
        spacerItem3 = QtWidgets.QSpacerItem(410, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.label_6 = QtWidgets.QLabel(self.frame_dnd)
        self.label_6.setStyleSheet("\n"
"background:#1d3557;font: 10pt \"Arial Rounded MT\";\n"
"color:#A20000;\n"
"\n"
"background:white;\n"
"font-weight:500;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_filename = QtWidgets.QLabel(self.frame_dnd)
        self.label_filename.setStyleSheet("\n"
"background:#1d3557;font: 10pt \"Arial Rounded MT\";\n"
"color:#545454;\n"
"\n"
"background:white;\n"
"font-weight:500;")
        self.label_filename.setText("")
        self.label_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.label_filename.setObjectName("label_filename")
        self.verticalLayout_7.addWidget(self.label_filename)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_dnd)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setSpacing(18)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_contrast_icon = QtWidgets.QLabel(self.frame_4)
        self.label_contrast_icon.setMinimumSize(QtCore.QSize(25, 25))
        self.label_contrast_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.label_contrast_icon.setText("")
        self.label_contrast_icon.setPixmap(QtGui.QPixmap(":/icons/icons/contrast-icon.png"))
        self.label_contrast_icon.setScaledContents(True)
        self.label_contrast_icon.setObjectName("label_contrast_icon")
        self.gridLayout.addWidget(self.label_contrast_icon, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(150, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.lineEdit_output_folder = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_output_folder.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_output_folder.sizePolicy().hasHeightForWidth())
        self.lineEdit_output_folder.setSizePolicy(sizePolicy)
        self.lineEdit_output_folder.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_output_folder.setStyleSheet("background:#888888;\n"
"border-radius:5px;\n"
"    font: 10pt \"MS Sans Serif\";\n"
"border:2px solid #C4C4C4;\n"
"padding:5px;\n"
"color:#a8dadc;\n"
"color:white;")
        self.lineEdit_output_folder.setText("")
        self.lineEdit_output_folder.setObjectName("lineEdit_output_folder")
        self.gridLayout.addWidget(self.lineEdit_output_folder, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.horizontalSlider_contrast = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider_contrast.setStyleSheet("            QSlider::groove:horizontal {\n"
"background: white;\n"
"height: 7px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: rgba(17, 168, 0);\n"
"border: 1px solid rgb(17, 168, 0);\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #A2A2A2;\n"
"border: 1px solid #A2A2A2;\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(17, 168, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid rgb(17, 168, 0);\n"
"width: 15px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: rgb(17, 168, 0);\n"
"border: 1px solid #A2A2A2;\n"
"width: 15px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.horizontalSlider_contrast.setMaximum(127)
        self.horizontalSlider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_contrast.setObjectName("horizontalSlider_contrast")
        self.gridLayout.addWidget(self.horizontalSlider_contrast, 1, 1, 1, 1)
        self.horizontalSlider_brightness = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider_brightness.setStyleSheet("            QSlider::groove:horizontal {\n"
"background: white;\n"
"height: 7px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: rgba(17, 168, 0);\n"
"border: 1px solid rgb(17, 168, 0);\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #A2A2A2;\n"
"border: 1px solid #A2A2A2;\n"
"height: 10px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(17, 168, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid rgb(17, 168, 0);\n"
"width: 15px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: rgb(17, 168, 0);\n"
"border: 1px solid #A2A2A2;\n"
"width: 15px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.horizontalSlider_brightness.setMaximum(100)
        self.horizontalSlider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_brightness.setObjectName("horizontalSlider_brightness")
        self.gridLayout.addWidget(self.horizontalSlider_brightness, 2, 1, 1, 1)
        self.label_colormap = QtWidgets.QLabel(self.frame_4)
        self.label_colormap.setMinimumSize(QtCore.QSize(250, 35))
        self.label_colormap.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_colormap.setStyleSheet("")
        self.label_colormap.setText("")
        self.label_colormap.setScaledContents(True)
        self.label_colormap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_colormap.setObjectName("label_colormap")
        self.gridLayout.addWidget(self.label_colormap, 4, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_infrared_toggle = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_infrared_toggle.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_infrared_toggle.setObjectName("horizontalLayout_infrared_toggle")
        self.gridLayout.addWidget(self.frame_6, 3, 1, 1, 1)
        self.label_brightness_icon = QtWidgets.QLabel(self.frame_4)
        self.label_brightness_icon.setMinimumSize(QtCore.QSize(25, 25))
        self.label_brightness_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.label_brightness_icon.setText("")
        self.label_brightness_icon.setPixmap(QtGui.QPixmap(":/icons/icons/brightness-icon.png"))
        self.label_brightness_icon.setScaledContents(True)
        self.label_brightness_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_brightness_icon.setObjectName("label_brightness_icon")
        self.gridLayout.addWidget(self.label_brightness_icon, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.btn_start_processing = QtWidgets.QPushButton(self.frame_7)
        self.btn_start_processing.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_processing.sizePolicy().hasHeightForWidth())
        self.btn_start_processing.setSizePolicy(sizePolicy)
        self.btn_start_processing.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.btn_start_processing.setStyleSheet("background:#870000;\n"
"font: 12pt \"MS Reference Sans Serif\";\n"
"color:white;\n"
"padding:10px 50px;\n"
"border-radius:10px;")
        self.btn_start_processing.setObjectName("btn_start_processing")
        self.horizontalLayout_7.addWidget(self.btn_start_processing)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_processed_frame = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_processed_frame.sizePolicy().hasHeightForWidth())
        self.label_processed_frame.setSizePolicy(sizePolicy)
        self.label_processed_frame.setMinimumSize(QtCore.QSize(500, 500))
        self.label_processed_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_processed_frame.setText("")
        self.label_processed_frame.setScaledContents(True)
        self.label_processed_frame.setObjectName("label_processed_frame")
        self.verticalLayout_3.addWidget(self.label_processed_frame)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame_main)
        self.frame = QtWidgets.QFrame(self.bgApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(1116, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.frame_size_grip = QtWidgets.QFrame(self.frame)
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_2.addWidget(self.frame_size_grip)
        self.verticalLayout_4.addWidget(self.frame)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)
        self.actionImport_Lists = QtWidgets.QAction(MainWindow)
        self.actionImport_Lists.setObjectName("actionImport_Lists")
        self.actionView_Lists_Data = QtWidgets.QAction(MainWindow)
        self.actionView_Lists_Data.setObjectName("actionView_Lists_Data")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLists_Settings = QtWidgets.QAction(MainWindow)
        self.actionLists_Settings.setObjectName("actionLists_Settings")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionABC = QtWidgets.QAction(MainWindow)
        self.actionABC.setObjectName("actionABC")
        self.actionDEF = QtWidgets.QAction(MainWindow)
        self.actionDEF.setObjectName("actionDEF")
        self.actionABC_2 = QtWidgets.QAction(MainWindow)
        self.actionABC_2.setObjectName("actionABC_2")
        self.actionDEF_2 = QtWidgets.QAction(MainWindow)
        self.actionDEF_2.setObjectName("actionDEF_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ColorVSN"))
        self.label.setText(_translate("MainWindow", "ColorVSN"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.label_5.setText(_translate("MainWindow", "Drop a file here or click to upload"))
        self.label_6.setText(_translate("MainWindow", "Maximum File Size: 3GB"))
        self.label_2.setText(_translate("MainWindow", "Contrast"))
        self.label_4.setText(_translate("MainWindow", "Brightness"))
        self.label_9.setText(_translate("MainWindow", "Output Folder"))
        self.label_8.setText(_translate("MainWindow", "Colormap"))
        self.lineEdit_output_folder.setPlaceholderText(_translate("MainWindow", "Input Output Folder Path"))
        self.label_7.setText(_translate("MainWindow", "Infrared"))
        self.btn_start_processing.setText(_translate("MainWindow", "Start Processing"))
        self.groupBox.setTitle(_translate("MainWindow", "Preview"))
        self.actionImport_Lists.setText(_translate("MainWindow", "Import Lists"))
        self.actionView_Lists_Data.setText(_translate("MainWindow", "View Lists"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLists_Settings.setText(_translate("MainWindow", "Lists Settings"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionABC.setText(_translate("MainWindow", "ABC"))
        self.actionDEF.setText(_translate("MainWindow", "DEF"))
        self.actionABC_2.setText(_translate("MainWindow", "ABC"))
        self.actionDEF_2.setText(_translate("MainWindow", "DEF"))
import resources_rc
